import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import AppContextProvider from "@/components/AppContext";
import ChatWindow from "@/components/chatwindow/ChatWindow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
             <div className="flex h-screen overflow-hidden"> 
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <SidebarProvider>
                  <AppContextProvider>
                  
                      
                      {/* 侧边栏：宽度固定或由 Sidebar 组件自己控制 */}
                      <AppSidebar/> 
                      
                      {/* 主内容区：flex-1 让其占据剩余所有宽度 */}
                      <main className="flex-1 overflow-y-auto"> 
                          <ChatWindow/>
                          {children}
                      </main>
                      
                  
                  </AppContextProvider>
                </SidebarProvider>
              </ThemeProvider>
              </div>
        </body>
      </html>
    </>
  );
}
